development:
  access_key_id: AKIAJ4NHN5IJRYPYCJYQ
  secret_access_key: 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

production:
  access_key_id: AKIAJ4NHN5IJRYPYCJYQ
  secret_access_key: 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